-----BRAND----

CREATE TABLE BRAND(
 ID NUMBER PRIMARY KEY,
 B_NAME VARCHAR2(200),
 ACTIVE NUMBER
)

-------CATEGORY-------

CREATE TABLE CATEGORY(
 ID NUMBER PRIMARY KEY,
 CAT_NAME VARCHAR2(200),
 PID_NUMBER NUMBER,
 CREATE_BY NUMBER,
 CREATE_ON DATE,
 COMPANY_ID NUMBER,
 ACTIVE NUMBER
)

-----CUSTOMER INFO------

CREATE TABLE CUSTOMER_INFO(
 ID NUMBER PRIMARY KEY,
 CUST_NAME VARCHAR2(200),
 CUST_ADDRESS VARCHAR2(200), 
 ADDRESS2 VARCHAR2(200),
 PHONE_NO NUMBER,
 NATIONALITY NUMBER,
 GENDER NUMBER,
 RELIGION NUMBER,
 CREDIT_LIMT NUMBER,
 CREATE_BY VARCHAR2(200),
 CREATE_ON DATE, 
 COMPANY_ID NUMBER,
 ACTIVE NUMBER
)


-----ITEM MASTER--------

CREATE TABLE ITEM_MASTER(
 ID NUMBER PRIMARY KEY,
 ITEM_NO NUMBER,
 ITEM_NAME VARCHAR2(200),
 UOM NUMBER,
 CAT_NAME VARCHAR2(200),
 B_NAME VARCHAR2(200),
 PUR_RATE NUMBER,
 SAL_RATE NUMBER,
 RE_ORDER NUMBER,
 ITEM_IMG BLOB,
 CREATE_BY VARCHAR2(200),
 CREATE_ON DATE,
 COMPANY_ID NUMBER, 
 ACTIVE NUMBER
)

------ PO DETAIL-----

CREATE TABLE PO_DETAIL(
 ID NUMBER PRIMARY KEY,
 PO_NO NUMBER,
 ITEM_NAME VARCHAR2(200),
 UOM NUMBER,
 RATE NUMBER,
 QTY NUMBER
)

------PO ORDER--------

CREATE TABLE PO_ORDER(
 PO_NO NUMBER,
 PO_ID NUMBER PRIMARY KEY,
 PO_DATE DATE,
 PO_SUPP VARCHAR2(200),
 AMOUNT NUMBER,
 DISCOUNT NUMBER,
 VAT NUMBER,
 NET_AMOUNT NUMBER,
 CREATE_BY VARCHAR2(200),
 CREATE_ON DATE, 
 COMPANY_ID NUMBER,
 CN_FLAG NUMBER,
 CN_DATE DATE,
 CN_BY VARCHAR2(200),
 CN_REASON VARCHAR2(200),
 APP_FLAG NUMBER,
 APP_DATE DATE,
 APP_BY VARCHAR2(200)
)

-------SALES ORDER---------
CREATE TABLE SALES_ORDER(
 ORDER_NO NUMBER,
 ORDER_ID NUMBER PRIMARY KEY,
 ORDER_DATE DATE ,
 CUSTOMER_NAME VARCHAR2(200),
 ORDER_ADDRESS VARCHAR2(200),
 PAY_TYPE NUMBER,
 AMOUNT NUMBER,
 VAT_PER NUMBER ,
 VAT_AMT NUMBER,
 SUB_AMT NUMBER,
 DIS_PER NUMBER,
 DIS_AMT NUMBER,
 NET_AMOUNT NUMBER,
 CREATE_BY VARCHAR2(200),
 CREATE_ON DATE,
 COMPANY_NO NUMBER
)

---- SALES ORDER DETAIL-----

CREATE TABLE SALES_ORDER_DETAIL(
 ORDER_ID NUMBER PRIMARY KEY,
 ORDER_NO NUMBER,
 ITEM_NO NUMBER,
 RATE NUMBER,
 QTY NUMBER
)

----- SUPPLIER INFO-----

CREATE TABLE SUPPLIER_INFO(
 ID NUMBER PRIMARY KEY,
 SUPP_NAME VARCHAR2(200),
 ADDRESS1 VARCHAR2(200),
 ADDRESS2 VARCHAR2(200),
 PHONE NUMBER,
 PHONE2 NUMBER,
 EMAIL VARCHAR2(200),
 ACTIVE NUMBER
)

-------UOM------

CREATE TABLE UOM(
 ID NUMBER PRIMARY KEY,
 UNIT_NAME VARCHAR2(200)
)
